# Generated by Django 2.1.7 on 2019-03-03 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('NoLines', models.IntegerField(max_length=3)),
                ('Start_date', models.DateTimeField(auto_now_add=True)),
                ('End_date', models.DateTimeField()),
                ('Genre', models.CharField(max_length=200)),
                ('Status', models.BooleanField()),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JamLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNo', models.IntegerField(max_length=3)),
                ('Line', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
