# Generated by Django 2.1.7 on 2019-03-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jam',
            name='Genre',
        ),
        migrations.AddField(
            model_name='jam',
            name='cover',
            field=models.ImageField(default='jam_covers/cover.jpg', upload_to='jam_covers/'),
        ),
        migrations.AlterField(
            model_name='jam',
            name='NoLines',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jamlines',
            name='LineNo',
            field=models.IntegerField(),
        ),
    ]
