# Generated by Django 2.1.7 on 2019-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_auto_20190310_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='End_date',
            field=models.DateTimeField(null=True),
        ),
    ]
