# Generated by Django 2.1.7 on 2019-03-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_auto_20190310_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamlines',
            name='Jamid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jam.Jam'),
        ),
    ]
