# Generated by Django 2.1.7 on 2019-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0004_jamlines_jamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamlines',
            name='Line',
            field=models.CharField(max_length=100),
        ),
    ]
